name: android e2e emulator test

on: push

jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: pull the project in runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium@1.22
          appium -v
          appium &>/dev/null &
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Dsurefire.suiteXmlFiles=androidSmoketestng.xml -Dplatform=android || true

      - name: Upload Appium logs
        uses: actions/upload-artifact@v2
        with:
          name: appium-logs
          path: appium.log
